services:
  redis:
    image: redis:8.0.3
    ports:
      - "6379:6379"
    command: ["redis-server","--save","60","1","--loglevel","warning"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data: